### ISSUE TITLE
write the word "Do it again" repeatedly

### ISSUE THREAD

**Issue by Ivanaix** [adamlui/chatgpt-apps#76]
When you open chatgpt it starts writing the word "Do it again" indefinitely
![Captura de pantalla (3)](https://github.com/user-attachments/assets/8550783f-79b6-47aa-85a8-c88bfa6f97ed)

**Comment by adamlui** [comment]
hey @Ivanaix thank you for reporting this, the cause is there is an OpenAI bug that causes new chats to sometimes reset suddenly so Infinity doesn't know to send the initial prompt again, but I just fixed it and submitted an update to the app stores

If you are using the userscript, to update click userscript manager icon in browser toolbar > scroll to ChatGPT Infinity > Check for updates > Update

If you are using the Chrome or Edge extension it will auto-update in 1~2 days for Chrome, and 3~4 days for Edge
