### ISSUE TITLE
Broken alignment of buttons in input field

### ISSUE THREAD

**Issue by mrbacky** [adamlui/chatgpt-apps#80]
Hi, noticed since a few days ago incorrect alignment of the buttons. Check the screenshot.

<img width="1511" alt="Screenshot 2024-09-11 at 23 00 51" src="https://github.com/user-attachments/assets/25304b3c-2bf4-4058-ac36-beaa40ba2fbd">

Tried to uninstall the extension and install again, but the problem persists.

**Comment by Spazz** [comment]
I was literally about to create this same issue. I think possibly the issue is openAI changing their message panel to use a div instead of a textarea element.

Possibly changing line 170 of the content.js file from and to below might resolve?

let chatbarBGdiv = document.querySelector('textarea') -- Broken

let chatbarBGdiv = document.getElementById('prompt-textarea') -- Maybe fix??


![image](https://github.com/user-attachments/assets/f878720e-6f45-48b5-8d04-beec93db0d24)

**Comment by adamlui** [comment]
Hey @mrbacky thank you for reporting the issue, OpenAI finally updated my UI today so I was able to fix the bug, if you are using the userscript, to update click userscript manager icon in browser toolbar > scroll to ChatGPT Widescreen > Check for updates > Update, if you are using Chrome extension it will auto-update sometime tonight or tomorrow after Chrome review
